# NumPy

###  1.Creación y vectorización

In [1]:
import numpy as np

arr1 = np.array([10,20,30,40])
arr2 = np.array([1,2,3,4])

#### Cálculos

In [3]:
resultado = arr1 + 5
print(resultado)

[15 25 35 45]


In [4]:
resultado = arr2 * arr1
print(resultado)

[ 10  40  90 160]


### 2.Indexación y filtrado booleano (Boolean Indexing)

In [5]:
edades = np.array([10,67,20,15,18])
es_mayor = edades >= 18
print(es_mayor)

[False  True  True False  True]


In [6]:
mayores_edadd = edades[edades>= 18]
print(mayores_edadd)

[67 20 18]


### 3.Métodos Estadísticos Rápidos

In [12]:
datos = np.array([10,15,20,25,100])

print(np.mean(datos))
print(np.median(datos))
print(np.std(datos))
print(np.sum(datos))
print(np.max(datos))

34.0
20.0
33.37663853655727
170
100


In [ ]:
#EJERCICIO 1

a1 = np.array([100,250,80,500])
resultado = a1 * 0.85
print(f"LA RESPUESTA DEL EJERCICIO 1 ES: {resultado}")


#EJERCICIO 2
a2 = np.array([28.5,31.0,24.2,35.5,21.0,33.8])
print(f"LA RESPUESTA DEL EJERCICIO 2 ES: {a2[a2 > 30]}")

#EJERCICIO 3
a3 = np.array([12,15,8,20,17,9,14])

print(f"LA RESPUESTA DEL EJERCICIO 3 ES: {len(a3[a3 >= 11])} ")



LA RESPUESTA DEL EJERCICIO 1 ES: [ 85.  212.5  68.  425. ]
LA RESPUESTA DEL EJERCICIO 2 ES: [31.  35.5 33.8]
LA RESPUESTA DEL EJERCICIO 3 ES: 5 
